frontend/models/Tree.php
<?php

namespace frontend\models;

use common\models\User;
use frontend\behaviors\IpBehavior;
use frontend\Entity;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "tree".
 *
 * @property integer $id
 * @property integer $type_id
 * @property integer $user_id
 * @property integer $status
 * @property number $deposit
 *
 * @property TreeType $type
 * @property User $user
 * @property ActiveQuery $members
 */
class Tree extends ActiveRecord
{
    use Entity;

    const OPEN = 51;
    const CLOSE = 52;
    const INSUFFICIENT_FUNDS = 61;
    const ADD_TO_CLOSED = 61;

    public static $statuses = [
        Tree::OPEN => 'Матрица открыта',
        Tree::CLOSE => 'Матрица закрыта',
        Tree::INSUFFICIENT_FUNDS => 'Недостаточно средств на счету',
        Tree::ADD_TO_CLOSED => 'Попытка добавиться в закрытую матрицу',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tree';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_id', 'user_id', 'status'], 'required'],
            [['type_id', 'user_id', 'status'], 'integer'],
//            ['user_id', 'exists',
//                'targetClass' => User::className(),
//                'targetAttribute' => 'id'
//            ],
            ['deposit', 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            IpBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'type_id' => Yii::t('app', 'Type ID'),
            'type' => Yii::t('app', 'Matrix'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @return \frontend\models\TreeType
     */
    public function getType()
    {
        return $this->hasOne(TreeType::className(), ['id' => 'type_id']);
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return Tree
     */
    public function getParent()
    {
        if ($this->user->parent_id) {
            return Tree::findOne([
                'user_id' => $this->user->parent_id,
                'type_id' => $this->type_id
            ]);
        }
        return null;
    }

    /**
     * @return ActiveQuery
     */
    public function getMembers() {
        $command = Yii::$app->db->createCommand('SELECT t.* FROM user u
          JOIN tree t ON u.id = t.user_id WHERE u.parent_id = :parent_id', [
            ':parent_id' => $this->user_id
        ]);
        $command->execute();
        while($tree = $command->pdoStatement->fetchObject(static::className())) {
            yield $tree;
        }
    }

    public function countMembers() {
        $command = Yii::$app->db->createCommand('SELECT count(*) FROM user u
          JOIN tree t ON u.id = t.user_id WHERE u.parent_id = :parent_id', [
            ':parent_id' => $this->user_id
        ]);
        $command->execute();
        return $command->pdoStatement->fetchColumn();
    }

    public function fee() {
        for($current = $this->user, $i = 1; $current->parent_id; $current = $current->parent, $i++);
        return $this->type->fee($i);
    }

    public function __toString() {
        return $this->user . ' ' . $this->type->name;
    }
}

frontend/models/TreeType.php
<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "tree_type".
 *
 * @property integer $id
 * @property string $name
 * @property integer $degree
 * @property integer $priority
 * @property number $stake
 * @property number $fee
 *
 * @property Tree[] $trees
 * @property ActiveQuery levels
 */
class TreeType extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tree_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name', 'string', 'min' => 3],
            [['degree', 'priority', 'stake', 'fee'], 'required'],
            [['degree', 'priority'], 'integer'],
            [['stake', 'fee'], 'number'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'degree' => Yii::t('app', 'Degree'),
            'priority' => Yii::t('app', 'Priority'),
            'stake' => Yii::t('app', 'Stake'),
            'fee' => Yii::t('app', 'Fee'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrees()
    {
        return $this->hasMany(Tree::className(), ['type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLevels()
    {
        return $this->hasMany(TreeLevel::className(), ['type_id' => 'id']);
    }

    /**
     * @param $i
     * @return TreeLevel
     */
    public function level($i) {
        $levels = $this->levels;
        $n = count($levels);
        for($j = 0; $j < $n; $j++) {
            if ($i == $levels[$j]->level)
                return $levels[$j];
        }
        return null;
    }

    /**
     * @param integer $i
     * @return float
     */
    public function interest($i) {
       $level = $this->level($i);
       return $level ? $level->interest : null;
    }

    public function __toString() {
        return $this->name;
    }
}

frontend/controllers/TreeController.php
<?php

namespace frontend\controllers;

use common\models\Log;
use common\models\User;
use Exception;
use frontend\Entity;
use frontend\LogEvent;
use PDO;
use Yii;
use frontend\models\Tree;
use frontend\models\TreeSearch;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\JqueryAsset;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TreeController implements the CRUD actions for Tree model.
 */
class TreeController extends Controller
{
    use Entity;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tree models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TreeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tree model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tree model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tree();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Tree model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \yii\db\Exception
     */
    public function actionOpen()
    {
        $user = Yii::$app->user->identity;
        if (Tree::find()->where(['user_id' => $user->id])->count() > 0) {
            return $this->redirect('matrix');
        }
        if (isset($_POST['agree']) && 1 == $_POST['agree']) {
            $transaction = Yii::$app->db->beginTransaction();
            $model = new Tree();
            $model->user_id = $user->id;
            $model->type_id = 1;
            try {
                if ($user->account >= $model->type->stake) {
                    Yii::$app->db->createCommand('CALL enter(:user_id, 1)', [
                        ':user_id' => $user->id
                    ])->execute();
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', 'Матрица открыта');
                    Log::log(Tree::CLOSE, $model->user_id);
                    return $this->redirect(['matrix', 'id' => $model->id]);
                }
                else {
                    throw new Exception('Недостаточно средств на счету');
                }

            }
            catch (Exception $ex) {
                $transaction->rollBack();
                if ($ex instanceof LogEvent) {
                    $ex->log();
                }
                Yii::$app->session->setFlash('error', $ex->getMessage());
            }
        }

        return $this->render('open');
    }

    /**
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionMatrix()
    {
        $command = Yii::$app->db->createCommand('CALL descend(:user_id)', [
            ':user_id' => Yii::$app->user->id
        ]);
        $command->execute();
        $st = $command->pdoStatement;
        $models = $st->rowCount() > 0 ? $st->fetchAll(PDO::FETCH_NUM) : [];
        Yii::$app->view->registerJsFile('//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js', [
            'depends' => [JqueryAsset::className()]
        ]);
        Yii::$app->view->registerCssFile('//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css');
        return $this->render('matrix', [
            'models' => $models
        ]);
    }

    /**
     * Updates an existing Tree model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Tree model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tree model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tree the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tree::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

class TreeException extends Exception {
    public $id;
    public $code;

    public function __construct($id, $code, $message = null) {
        $this->id = $id;
        $this->code = $code;
        $this->message = Tree::$statuses[$code];
        if ($message) {
            $user_id = Yii::$app->user->id;
            Yii::error("$id\t$code\t$user_id\t$message", 'perfect');
        }
        Log::log($code);
    }
}

frontend/views/tree/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Tree */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tree-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'type_id')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord
            ? Yii::t('app', 'Create')
            : Yii::t('app', 'Update'),
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/tree/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\TreeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tree-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'type_id') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/tree/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Tree */

$this->title = Yii::t('app', 'Create Tree');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trees'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/tree/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\TreeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Trees');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Tree'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model, $key, $index, $widget) {
            return Html::a(Html::encode($model->id), ['view', 'id' => $model->id]);
        },
    ]) ?>

</div>

frontend/views/tree/matrix.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Матрица');
$this->params['breadcrumbs'][] = $this->title;
echo Html::tag('script', 'var tree = ' . json_encode($models));
?>
<div class="tree-matrix">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (count($models) == 0): ?>
        <?= Html::a(Yii::t('app', 'Open'), ['tree/open'], ['class' => 'btn btn-primary']); ?>
    <?php endif ?>
    <table id="matrix"></table>
    <table id="level"></table>
</div>

frontend/views/tree/open.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Открытие матрицы');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-open">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin() ?>

    <?= Html::hiddenInput('agree', true) ?>

    <?= Html::submitButton(Yii::t('app', 'Open'), ['class' => 'btn btn-success']) ?>

    <?php ActiveForm::end() ?>
</div>

frontend/views/tree/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Tree */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Tree',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trees'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="tree-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/tree/view.php
<?php

use frontend\models\Tree;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Tree */

$this->title = $model->type->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trees'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if(Yii::$app->user->can('manage')): ?>
    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php endif ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'type',
                'format' => 'html',
                'value' => Html::a($model->type, ['tree-type/view', 'id' => $model->type_id])
            ],
            [
                'attribute' => 'status',
                'value' => Tree::$statuses[$model->status]
            ],
        ],
    ]) ?>

</div>